### ISSUE TITLE
要不要把 shruby.org 这个域名买下来?

### ISSUE THREAD

**Issue by zhouguangming** [shruby/shruby.github.io#39]
godaddy 有售, 裸价 $9.99.

**Comment by xiaoronglv** [comment]
http://shruby.org

1. 域名已买
2. 配置好了

要不要把代码托管转移到 Gitcafe 中？Github 在国内的访问速度太慢了。

**Comment by zhouguangming** [comment]
:+1:

**Comment by bachue** [comment]
@xiaoronglv 这个建议很早之前就被我否决过一次 原因是没有CI
